//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entrevista_DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat_conversacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chat_conversacion()
        {
            this.Mensajes_conversacion = new HashSet<Mensajes_conversacion>();
        }
    
        public int id_chat_conversacion { get; set; }
        public int usuarios_id_usuarios { get; set; }
        public Nullable<System.DateTime> fecha_inicio_conversacion { get; set; }
        public Nullable<System.DateTime> fecha_fin_conversacion { get; set; }
        public string titulo_conversacion { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensajes_conversacion> Mensajes_conversacion { get; set; }
    }
}
