//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entrevista_DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intentos_login
    {
        public int id_intentos_login { get; set; }
        public Nullable<int> usuarios_id_usuarios { get; set; }
        public Nullable<bool> exito_intento { get; set; }
        public Nullable<System.DateTime> fecha_intento { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
