//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entrevista_DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensajes_conversacion
    {
        public int id_mensaje { get; set; }
        public int chat_conversacion_id { get; set; }
        public string remitente { get; set; }
        public string mensaje { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
    
        public virtual Chat_conversacion Chat_conversacion { get; set; }
    }
}
