//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entrevista_DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SDEEntities : DbContext
    {
        public SDEEntities()
            : base("name=SDEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chat_conversacion> Chat_conversacion { get; set; }
        public virtual DbSet<Dificultad> Dificultad { get; set; }
        public virtual DbSet<Entrevista> Entrevista { get; set; }
        public virtual DbSet<Intentos_login> Intentos_login { get; set; }
        public virtual DbSet<Mensajes_conversacion> Mensajes_conversacion { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Planes_entrenamiento> Planes_entrenamiento { get; set; }
        public virtual DbSet<Preguntas> Preguntas { get; set; }
        public virtual DbSet<Recuperacion_password> Recuperacion_password { get; set; }
        public virtual DbSet<Respuestas> Respuestas { get; set; }
        public virtual DbSet<Resultado> Resultado { get; set; }
        public virtual DbSet<Sesiones> Sesiones { get; set; }
        public virtual DbSet<Temas> Temas { get; set; }
        public virtual DbSet<Tokens_login> Tokens_login { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
