//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entrevista_DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfil
    {
        public int id_perfil { get; set; }
        public int usuarios_id_usuarios { get; set; }
        public string avatar_seed { get; set; }
        public string avatar_estilo { get; set; }
        public string avatar_url { get; set; }
        public string bio { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
