//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entrevista_DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recuperacion_password
    {
        public int id_recuperacion { get; set; }
        public int usuarios_id_usuarios { get; set; }
        public string token_recuperacion { get; set; }
        public System.DateTime expiracion_token_recuperacion { get; set; }
        public Nullable<bool> usado_token_recuperacion { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
