//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entrevista_DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuestas
    {
        public int id_respuesta { get; set; }
        public int preguntas_id_pregunta { get; set; }
        public int entrevista_id_entrevista { get; set; }
        public string respuesta_usuario { get; set; }
        public Nullable<System.DateTime> fecha_respuesta { get; set; }
    
        public virtual Entrevista Entrevista { get; set; }
        public virtual Preguntas Preguntas { get; set; }
    }
}
