//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entrevista_DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sesiones
    {
        public int id_sesion { get; set; }
        public int usuarios_id_usuarios { get; set; }
        public string ip_sesion { get; set; }
        public string dispositivo { get; set; }
        public Nullable<System.DateTime> fecha_inicio_sesion { get; set; }
        public Nullable<System.DateTime> fecha_cierre_sesion { get; set; }
        public string token_sesion { get; set; }
        public bool activa { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
