//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entrevista_DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tokens_login
    {
        public int id_tokens_login { get; set; }
        public int usuarios_id_usuarios { get; set; }
        public string token { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime fecha_expiracion { get; set; }
        public bool token_activo { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
